import java.util.Arrays;
import java.util.List;

public class LoremIpsum {
    private static final String TEXT_LOREM_ISPUM = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis dictum in risus et feugiat. Maecenas tempus volutpat luctus. Quisque a feugiat nisl. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam laoreet aliquam risus, feugiat feugiat erat vestibulum vitae. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi tincidunt nec leo sed placerat. Fusce quis finibus elit, sed mollis mauris.\n" +
            "Cras dictum elementum augue at mollis. Cras auctor venenatis bibendum. In volutpat a eros eu sodales. Nulla sapien nisl, ultrices ullamcorper consequat at, facilisis vitae quam. Aenean scelerisque aliquam faucibus. Nunc accumsan nibh nibh, ut blandit mi porta et. Mauris non feugiat ipsum. Proin commodo commodo metus non eleifend. Nunc cursus turpis at vestibulum maximus. Vivamus rhoncus risus sed magna convallis interdum.\n" +
            "Nulla imperdiet, odio id euismod venenatis, nunc elit elementum dolor, ac rutrum nisi eros eget quam. Ut tempus dui odio, ac dictum tortor semper eget. Aliquam vel commodo neque. Praesent sollicitudin, dolor id molestie accumsan, eros risus interdum nunc, non blandit sem eros sed elit. Nulla tincidunt, nulla ut facilisis dapibus, nibh lacus cursus dui, sit amet sagittis orci ligula eget elit. Nullam libero velit, fringilla vitae varius sit amet, placerat quis dolor. Nullam venenatis, dolor sed accumsan consectetur, ante neque elementum velit, ultricies fringilla enim dui et lorem.\n" +
            "Suspendisse porta varius dolor, non ultricies lacus finibus a. Quisque eget hendrerit neque, ut posuere lorem. Praesent venenatis malesuada orci, ut dapibus mi ultricies sed. Proin ultricies sem lorem, a ullamcorper nisl commodo mollis. Maecenas lobortis, nibh ac elementum dapibus, turpis ante lacinia eros, in posuere est lectus ac arcu. Duis tincidunt vel nulla sed pellentesque. Mauris commodo pellentesque leo lobortis rhoncus. Fusce velit dolor, eleifend eu volutpat molestie, lobortis et justo. Pellentesque accumsan imperdiet nibh, luctus eleifend sem ultricies euismod. Mauris a consectetur enim, vitae pharetra metus. Integer pellentesque risus massa, vel venenatis justo sagittis vel. Pellentesque eu elit nec mi consequat ullamcorper. Aenean non consectetur nunc, at ultricies magna. Aenean id lacus quis diam aliquam semper sit amet sed est.\n" +
            "Donec eget dapibus risus. Aliquam pretium tristique purus, sit amet aliquet dolor aliquet at. Morbi hendrerit est eget neque mollis semper. Duis non finibus ligula, nec gravida lectus. Nulla facilisi. Vestibulum facilisis neque ut faucibus faucibus. Donec eget tortor at urna ullamcorper tempor. Ut eu dui lacus. Fusce sollicitudin, turpis non facilisis faucibus, metus metus tempor turpis, eu posuere est lacus ut risus. Aliquam et mauris ex. Maecenas in ultrices tellus.\n" +
            "Duis sit amet ultrices ex, at aliquet neque. Phasellus id odio vitae odio iaculis aliquam. Maecenas at neque rhoncus, ultricies dolor vel, cursus lacus. Cras libero urna, blandit in finibus porta, bibendum non erat. Pellentesque sit amet condimentum nisl, sagittis fringilla ante. Etiam maximus nibh et diam iaculis mollis. Suspendisse fringilla ultricies auctor.\n" +
            "Nulla facilisi. Suspendisse porta eleifend turpis, ut vehicula metus aliquam nec. Praesent consectetur ac justo non luctus. Vivamus pretium aliquam elit, a accumsan sem efficitur nec. Praesent semper massa interdum nunc imperdiet, ultrices hendrerit orci interdum. Etiam vulputate sed dolor sit amet interdum. Nullam tempor venenatis mauris, et blandit justo tempus eget. In rhoncus feugiat ex a aliquet. Phasellus convallis velit vel turpis dictum porta. Sed sodales convallis nulla eu sodales. Pellentesque nec ligula consectetur, cursus leo eu, semper velit.\n" +
            "Cras risus quam, varius sed dolor quis, placerat finibus tortor. Nunc id augue in risus mollis feugiat ac et lectus. Nunc efficitur nec elit id sollicitudin. Integer vel neque tortor. Praesent id arcu odio. In hac habitasse platea dictumst. Morbi vitae ullamcorper lacus, id placerat dui. Integer at auctor lacus. Duis ligula nisi, laoreet eu felis pulvinar, feugiat aliquet metus. Aenean varius nisi ut sapien dictum aliquam.\n" +
            "Curabitur at bibendum elit. Nulla porttitor volutpat tellus eget rhoncus. Maecenas consequat pretium ipsum, pellentesque varius nulla egestas in. Aliquam erat volutpat. Etiam ornare quam eu velit dictum, at sagittis nisi ornare. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed vel felis rutrum, rutrum sem vitae, fringilla tortor. Ut quis facilisis ante, malesuada suscipit est. Phasellus massa sem, elementum sit amet augue in, tristique sollicitudin tortor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;\n" +
            "Nam tristique viverra nulla id ultricies. Cras tortor nulla, rutrum id vehicula ac, laoreet et metus. Mauris vitae diam vehicula, feugiat justo vitae, varius orci. Integer id nulla erat. Maecenas tellus turpis, lobortis vel neque nec, auctor porta sem. Curabitur varius tellus eu luctus porta. Nam malesuada tellus non pretium ullamcorper. Praesent felis augue, posuere tristique pulvinar vel, finibus vel tortor. Suspendisse varius orci a massa consectetur dignissim. Proin laoreet malesuada lectus ac accumsan. Sed vestibulum sodales felis, eu lobortis diam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae\n";

    public LoremIpsum() {
    }

    public List<String> getTextArray() {
        return Arrays.asList(TEXT_LOREM_ISPUM.split("\n"));
    }
}
